# Generated by Django 3.2.3 on 2021-07-20 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0002_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Principle',
            new_name='principle',
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
