# Generated by Django 3.2.5 on 2021-07-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0008_auto_20210720_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloan',
            name='status',
            field=models.CharField(choices=[('Nw', 'New'), ('Rq', 'Request'), ('Rj', 'Rejected'), ('Ap', 'Approved')], default='Nw', max_length=2),
        ),
    ]
