# Generated by Django 3.2.5 on 2021-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0009_alter_userloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='loan_status',
            field=models.CharField(choices=[('Nw', 'New'), ('Rq', 'Request'), ('Rj', 'Rejected'), ('Ap', 'Approved')], default='Nw', max_length=2),
        ),
    ]
