# Generated by Django 3.2.5 on 2021-07-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0010_userloan_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloan',
            name='status',
        ),
    ]
