# Generated by Django 3.2.5 on 2021-07-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0014_alter_userloan_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='emi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
