# Generated by Django 3.2.5 on 2021-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0015_userloan_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloan',
            name='tenure',
            field=models.FloatField(),
        ),
    ]
