# Generated by Django 3.2.5 on 2021-07-21 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0017_alter_userloan_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userloan',
            name='emi',
            field=models.FloatField(blank=True),
        ),
    ]
