# Generated by Django 3.2.5 on 2021-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0018_auto_20210721_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
