# Generated by Django 4.0 on 2022-05-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0019_userloan_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dependents', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('G', 'Graduated'), ('N', 'NOt Graduated')], max_length=1)),
                ('self_employed', models.BooleanField()),
                ('income', models.FloatField()),
                ('credit_history', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='loanPortal.user')),
            ],
        ),
    ]
