# Generated by Django 4.0 on 2022-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0020_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
