# Generated by Django 4.0 on 2022-05-13 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanPortal', '0021_accuracytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuracytable',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
